import {
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  max_newm_1,
  max_newm_2,
  max_newm_3,
  max_newm_4,
  max_newm_5,
  max_newm_6,
  max_newm_7,
  max_newm_8,
  max_newm_9,
  adidas_newm_1,
  adidas_newm_2,
  adidas_newm_3,
  lacoste_newm_1,
  lacoste_newm_2,
  superdry_newm_1,
  superdry_newm_2,
  superdry_newm_3,
  superdry_newm_4,
  superdry_newm_5,
  superdry_newm_6,
  superdry_newm_7,
  superdry_newm_8,
  superdry_newm_9,
  women1,
  women_1,
  women_2,
  women_3,
  women_4,
  basic_1,
  basic_2,
  basic_3,
  basic_4,
} from "../assets/images/index";

import "./style.css";

export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
];

export const SplOfferData = [
  {
    _id: "201",
    img: imprimante1,
    productName: "Mens",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Mens",
  },
  {
    _id: "202",
    img: imprimante2,
    productName: "Mens",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Mens",
  },
  {
    _id: "203",
    img: imprimante4,
    productName: "Mens",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Mens",
  },
  {
    _id: "204",
    img: imprimante5,
    productName: "Mens",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Mens",
  },
  {
    _id: "205",
    img: imprimante6,
    productName: "Mens",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Mens",
  },
  {
    _id: "206",
    img: imprimante7,
    productName: "Mens",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Mens",
  },
  {
    _id: "207",
    img: imprimante8,
    productName: "Mens",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Mens",
  },
  {
    _id: "208",
    img: imprimante9,
    productName: "Mens",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Mens",
  },
  {
    _id: "209",
    img: encre1,
    productName: "Womens",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "210",
    img: encre2,
    productName: "Womens",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "211",
    img: encre3,
    productName: "Womens",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "212",
    img: encre4,
    productName: "Womens",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "213",
    img: basic_1,
    productName: "Basic",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Basic",
  },
  {
    _id: "214",
    img: basic_2,
    productName: "Basic",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Basic",
  },
  {
    _id: "215",
    img: basic_3,
    productName: "Basic",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Basic",
  },
  {
    _id: "216",
    img: basic_4,
    productName: "Basic",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Basic",
  },
  {
    _id: "217",
    img: bac1,
    productName: "Graphic",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Superdry",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Graphic",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Superdry",
  },
  {
    _id: "220",
    img: bac3,
    productName: "Graphic",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Superdry",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Graphic",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Superdry",
  },
];

export const paginationItems = [
  {
    _id: "201",
    img: max_newm_1,
    productName: "Max Men's CA",
    price: "35.00",
    color: "Blue",
    badge: true,
    brand: "Max",
    des: "Max Men's Classic T-shirt - Timeless style and comfort define this Max branded men's t-shirt. Made for versatility and everyday wear, this classic tee boasts a sleek design and superior quality. Perfect for casual outings or layering under jackets, it's a wardrobe essential that combines effortless style with unbeatable comfort.",
    cat: "Mens",
    pdf: pdf1,
  },
  {
    _id: "202",
    img: max_newm_2,
    productName: "Max Men's Grey",
    price: "450",
    color: "Gray",
    badge: true,
    brand: "Max",
    des: "Introducing the Max Men's Plain Grey T-shirt - Elevate your everyday wardrobe with this essential piece from Max. Crafted from premium cotton, this plain grey tee offers a minimalist yet stylish look. Its versatile design makes it perfect for any casual occasion, while its soft fabric ensures all-day comfort. Whether you're running errands or meeting friends for coffee, this classic t-shirt is sure to become a go-to staple in your closet, effortlessly blending simplicity with sophistication.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "203",
    img: max_newm_3,
    productName: "Max Men's Off-Grey",
    price: "450",
    color: "Gray",
    badge: true,
    brand: "Max",
    des: "Meet the Max Men's Light Gray T-shirt - A contemporary take on timeless style. This light gray tee from Max combines classic design with modern comfort. Crafted from soft, breathable fabric, it's perfect for everyday wear. The subtle hue adds a touch of sophistication to your casual look, while the relaxed fit ensures all-day comfort. Whether you're lounging at home or out and about, this versatile t-shirt effortlessly pairs with your favorite jeans or shorts for a laid-back yet polished ensemble.",
    cat: "Mens",
    pdf: pdf1,
  },
  {
    _id: "2005",
    img: max_newm_4,
    productName: "Max Men's Typo Blue",
    price: "450",
    color: "Blue",
    badge: true,
    brand: "Max",
    des: "Introducing the Max Men's Blue Typographic T-shirt - Make a statement with style. Crafted in a calming shade of blue, this tee from Max adds a touch of personality to your casual wardrobe. Featuring a subtle typographic print, it adds just the right amount of detail without compromising on versatility. Made from soft, lightweight fabric, it ensures a comfortable fit all day long. Whether you're running errands or meeting friends, this unique piece effortlessly blends comfort with contemporary flair, making it a must-have addition to your collection.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "20005",
    img: max_newm_5,
    productName: "Max Men's Tshirt Red",
    price: "450",
    color: "Red",
    badge: true,
    brand: "Max",
    des: "Introducing the Max Men's Plain Red T-shirt - Bold simplicity meets unmatched comfort. This vibrant red tee from Max is the epitome of effortless style. Crafted from premium cotton, it offers a luxuriously soft feel against your skin. Its plain design allows for versatile pairing with your favorite jeans or shorts, making it a go-to choice for any casual occasion. Whether you're relaxing at home or exploring the city streets, this classic red tee ensures you stand out with confidence and comfort.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "206",
    img: max_newm_6,
    productName: "Max Men's Red-Grey",
    price: "450",
    color: "Red",
    badge: true,
    brand: "Max",
    des: "Introducing the Max Men's Reddish Maroon Typographic T-shirt - Elevate your casual look with a touch of sophistication. Crafted in a rich reddish maroon hue with subtle gray undertones, this tee from Max embodies understated elegance. Adorned with a small typographic print, it adds a hint of personality to your ensemble without overwhelming the simplicity of the design. Made from premium cotton blend fabric, it ensures superior comfort all day long. Perfect for casual outings or laid-back weekends, this unique piece effortlessly combines style and comfort for a look that's both refined and relaxed.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "207",
    img: max_newm_7,
    productName: "Max Men's Greenish-Yellow",
    price: "450",
    color: "Yellow",
    badge: true,
    brand: "Max",
    des: "Introducing the Max Men's Greenish Yellow Plain T-shirt - Embrace vibrant simplicity with this standout piece from Max. In a refreshing greenish yellow hue, this tee adds a pop of color to your wardrobe. Its plain design exudes effortless style, making it a versatile option for any casual occasion. Crafted from high-quality cotton, it offers a comfortable fit and a soft feel against the skin. Whether you're lounging at home or out and about, this greenish yellow tee is sure to brighten up your day with its fresh, laid-back charm.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "208",
    img: max_newm_8,
    productName: "Max Men's Bright Yellow",
    price: "450",
    color: "Yellow",
    badge: true,
    brand: "Max",
    des: "Introducing the Max Men's Bright Yellow Punky Plain T-shirt - Make a bold statement with a twist of punk-inspired fashion. This vibrant yellow tee from Max embodies a rebellious spirit with its edgy, punky plain style. Crafted to stand out, its vivid color commands attention while its minimalist design exudes effortless cool. Made from high-quality cotton, it offers both comfort and durability. Whether you're hitting the streets or rocking out at a concert, this tee adds a pop of personality to your look, making it a must-have for the fashion-forward individual who dares to be different.",
    cat: "Mens",
    pdf: pdf1,
  },
  {
    _id: "233",
    img: max_newm_9,
    productName: "Max Men's Emerald Green",
    price: "450",
    color: "Green",
    badge: true,
    brand: "Max",
    des: "Introducing the Max Men's Emerald Green Plain T-shirt - Elevate your wardrobe with a touch of sophistication in this rich emerald green tee from Max. Its deep, luxurious hue exudes elegance while maintaining a sense of effortless simplicity. Crafted from premium cotton, it offers a soft and comfortable fit that lasts all day. With its plain design, this tee is a versatile staple that seamlessly transitions from casual outings to more refined occasions. Whether paired with jeans for a laid-back vibe or dressed up under a blazer for a polished look, this emerald green tee adds a touch of refinement to any ensemble.",
    cat: "Mens",
    pdf: pdf1,
  },
  {
    _id: "220",
    img: superdry_newm_1,
    productName: "Superdry New Red",
    price: "25.00",
    color: "Red",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Red Typographic T-shirt - Designed for the modern Gen Z individual who values style and quality, this vibrant red tee from Superdry is a true standout. Adorned with an abundance of typographic elements, it exudes a playful yet bold aesthetic that resonates with the Gen Z spirit. Crafted from superb quality fabric, it offers unparalleled comfort and durability, ensuring it withstands the test of time. Whether you're hitting the streets or hanging out with friends, this eye-catching tee effortlessly merges contemporary style with exceptional quality, making it a must-have addition to your wardrobe.",
    cat: "Graphic",
  },
  {
    _id: "221",
    img: superdry_newm_2,
    productName: "Superdry New Green",
    price: "220.00",
    color: "Green",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Green Typographic T-shirt - Elevate your casual look with a burst of fresh style. This vibrant green tee from Superdry is designed to catch eyes and turn heads. Featuring an array of typographic elements, it adds a playful twist to your ensemble while staying true to Superdry's signature quality. Crafted from premium materials, it offers superb comfort and durability, ensuring it remains a staple in your wardrobe for years to come. Whether you're out and about or simply hanging with friends, this green typographic tee is sure to make a statement wherever you go, reflecting your individuality and sense of style.",
    cat: "Graphic",
  },
  {
    _id: "215",
    img: basic_1,
    productName: "Basic Plain Grey",
    price: "25.00",
    color: "Gray",
    badge: true,
    des: "Introducing the Men's Basic Plain Gray Freefit T-shirt - Elevate your everyday wardrobe with this essential tee. Crafted for comfort and versatility, this plain gray t-shirt features a freefit design, offering ease of movement for any activity. Whether you're lounging at home or running errands, its relaxed silhouette ensures all-day comfort. Made from soft and durable fabric, it's a staple piece that pairs effortlessly with any outfit. Dress it up with jeans and sneakers for a casual yet polished look, or layer it under a jacket for added style. Embrace simplicity and comfort with this must-have basic gray tee.",
    cat: "Basic",
  },
  {
    _id: "216",
    img: basic_2,
    productName: "Basic Plain Blue",
    price: "220.00",
    color: "Blue",
    badge: true,
    des: "Introducing the Men's Blue Freefit Sweatfit T-shirt - Elevate your activewear collection with this versatile tee designed for both comfort and performance. Crafted with a freefit and sweatfit design, this blue t-shirt offers unrestricted movement and moisture-wicking properties, keeping you cool and dry during intense workouts. Whether you're hitting the gym or going for a run, its breathable fabric ensures maximum comfort. The vibrant blue color adds a stylish pop to your athletic ensemble. Pair it with your favorite workout shorts or track pants for a complete athletic look. Stay comfortable and focused on your fitness goals with this essential blue tee.",
    cat: "Basic",
  },
  {
    _id: "209",
    img: women_1,
    productName: "Womens Red GenZ",
    price: "25.00",
    color: "Red",
    badge: true,
    des: "Introducing our stylish GenZ Women's T-shirt in a striking red hue, blending affordability with exceptional quality. Crafted for the modern woman, this tee effortlessly combines comfort and style. Its vibrant color and sleek design make it a standout choice for any occasion. Embrace affordable luxury with this wardrobe essential, designed to keep you looking and feeling your best with every wear.",
    cat: "Womens",
  },
  {
    _id: "210",
    img: women_2,
    productName: "Womens Yellow Typo",
    price: "220.00",
    color: "Yellow",
    badge: true,
    des: "Introducing our vibrant yellow T-shirt adorned with captivating blue typography, designed to make a statement. Perfect for the bold and expressive individual, this tee adds a pop of color to your wardrobe while exuding a sense of youthful energy. Crafted with comfort in mind, it ensures you stay stylish and confident all day long. Elevate your casual look with this eye-catching piece that promises both style and quality.",
    cat: "Womens",
  },

  {
    _id: "211",
    img: women_3,
    productName: "Womens Blue Typo",
    price: "25.00",
    color: "Blue",
    badge: true,
    des: "Introducing our trendy blue T-shirt featuring striking green typography for a standout look. Designed for the fashion-forward individual, this tee adds a pop of color to your ensemble while exuding a sense of youthful vibrancy. Crafted with quality materials, it ensures comfort and durability for all-day wear. Elevate your casual wardrobe with this stylish piece that combines modern design with superior quality.",
    cat: "Womens",
  },
  {
    _id: "212",
    img: women_4,
    productName: "Womens Green GenZ",
    price: "220.00",
    color: "Green",
    badge: true,
    des: "Introducing our chic dark green GenZ T-shirt, featuring crisp white typography for a sleek and modern appeal. Perfect for the trendsetting GenZ individual, this tee combines style with comfort effortlessly. Crafted from high-quality materials, it promises durability and long-lasting wear. Elevate your casual look with this standout piece that exudes youthful energy and contemporary flair. Embrace your unique style with our GenZ T-shirt, designed to make a statement wherever you go.",
    cat: "Womens",
  },
  {
    _id: "213",
    img: basic_3,
    productName: "Basic Plain Red",
    price: "25.00",
    color: "Red",
    badge: true,
    des: "Introducing the Men's Red Freefit T-shirt for Slim Builds - Elevate your wardrobe with this tailored tee designed specifically for slender frames. Crafted with a freefit silhouette, this red t-shirt offers ample room for movement while maintaining a sleek and flattering fit. Perfect for skinny individuals, its design ensures a comfortable and stylish wear experience. Whether you're hitting the gym or heading out for a casual day, this tee keeps you feeling confident and comfortable. The vibrant red color adds a bold touch to your ensemble, making it a standout piece in your wardrobe. Pair it with slim-fit jeans or tailored trousers for a polished look that highlights your physique.",
    cat: "Basic",
  },
  {
    _id: "214",
    img: basic_4,
    productName: "Basic",
    price: "220.00",
    color: "Green",
    badge: true,
    des: "Introducing the Men's Emerald Green Freefit T-shirt - Elevate your style with a pop of vibrant color. This emerald green t-shirt offers both comfort and freedom of movement with its freefit design. Whether you're on the go or lounging at home, its relaxed silhouette ensures a comfortable fit for all-day wear. The striking emerald green hue adds a bold and refreshing touch to your wardrobe, making it a standout piece for any occasion. Pair it with your favorite jeans or shorts for a casual look, or layer it under a jacket for added style. Embrace versatility and comfort with this essential emerald green tee.",
    cat: "Basic",
  },

  {
    _id: "217",
    img: superdry_newm_3,
    productName: "Superdry Prussian Blue",
    price: "25.00",
    color: "Blue",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Prussian Blue Typographic T-shirt - Dive into the depths of style with this striking Prussian blue tee from Superdry. Infused with an eclectic mix of typographic elements, it's a visual delight that speaks volumes about your unique personality. Crafted with Superdry's renowned commitment to quality, this tee boasts both comfort and durability, making it a reliable choice for any occasion. Whether you're hitting the streets or chilling with friends, the bold hue and playful typography ensure you stand out from the crowd with effortless cool. Elevate your wardrobe with this Prussian blue masterpiece and make a statement that's as bold as you are.",
    cat: "Graphic",
  },
  {
    _id: "219",
    img: superdry_newm_9,
    productName: "Superdry Dark Blue",
    price: "220.00",
    color: "Blue",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Dark Blue Typographic T-shirt - Embrace the allure of sophistication with a twist of contemporary style. This dark red tee from Superdry captivates with its understated elegance, while the addition of dark blue typography adds a touch of modern flair. Crafted with meticulous attention to detail and Superdry's commitment to quality, this tee offers both comfort and durability. Whether you're navigating the urban landscape or unwinding with friends, its rich color and subtle typography make a statement without overwhelming your look. Elevate your wardrobe with this versatile piece, blending classic charm with a hint of urban edge.",
    cat: "Graphic",
  },

  {
    _id: "hp1",
    img: adidas_newm_1,
    productName: "Adidas Monochrome New",
    price: "450",
    color: "Gray",
    badge: true,
    brand: "Adidas",
    des: "Introducing the Adidas Men's Monochrome Typographic T-shirt - Elevate your streetwear with this sleek and modern tee from Adidas. Featuring a monochrome palette of black, white, and gray, this tee offers a minimalist yet bold look. Crafted with Adidas's signature comfort and quality, it ensures all-day wearability. With subtle typographic elements adding a touch of urban edge, this tee seamlessly blends style and functionality. Whether you're hitting the streets or hanging out with friends, this Adidas tee is sure to make a statement. Elevate your wardrobe with this monochrome masterpiece and showcase your sporty style with confidence.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "hp2",
    img: adidas_newm_2,
    productName: "Adidas Blue Monochrome",
    price: "450",
    color: "Blue",
    badge: true,
    brand: "Adidas",
    des: "Introducing the Adidas Men's Dark Blue and White Striped Typographic T-shirt - Elevate your casual wardrobe with a touch of sporty sophistication. This Adidas tee features a classic design with dark blue and white stripes, offering a timeless yet contemporary look. Crafted with Adidas's renowned quality and comfort, it ensures a comfortable fit for all-day wear. With subtle typographic elements adding a hint of athletic flair, this tee seamlessly blends style and functionality. Whether you're hitting the gym or heading out for a casual day, this Adidas tee is sure to elevate your ensemble. Make a statement with this versatile piece and showcase your sporty style with confidence.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "hp3",
    img: adidas_newm_3,
    productName: "Adidas Yellow Monochrome",
    price: "450",
    color: "Yellow",
    badge: true,
    brand: "Adidas",
    des: "Introducing the Adidas Men's Yellow and White Striped Graphic T-shirt - Elevate your athletic-inspired style with a burst of vibrant color. This Adidas tee features bold yellow and white stripes, adding a dynamic touch to your ensemble. Crafted with Adidas's signature blend of comfort and performance, it ensures a comfortable fit for any activity. With a subtle graphic element enhancing its sporty appeal, this tee seamlessly combines style and functionality. Whether you're hitting the gym or running errands, this Adidas tee is sure to keep you looking and feeling great. Stand out from the crowd with this eye-catching piece and showcase your sporty style with confidence.",
    cat: "Mens",
    pdf: pdf1,
  },
  {
    _id: "ricoh1",
    img: superdry_newm_4,
    productName: "Superdry Yellow-Green New",
    price: "450",
    color: "Yellow",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Yellow and Mustard Typographic T-shirt - Embrace the vibrancy of urban style with this unique tee from Superdry. Combining shades of yellow and mustard, it exudes a dynamic energy that's sure to turn heads. Adorned with typographic elements in complementary hues, it adds a playful twist to your ensemble. Crafted with Superdry's renowned attention to detail and quality, this tee offers both comfort and durability. Whether you're exploring the city streets or hanging out with friends, its bold colors and eye-catching typography make a statement that's as bold as your personality. Step up your style game with this must-have addition to your wardrobe.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "ricoh2",
    img: superdry_newm_5,
    productName: "Superdry Neon Yellow",
    price: "450",
    color: "Yellow",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Neon Yellow Typographic T-shirt - Illuminate your wardrobe with this electrifying neon yellow tee from Superdry. Designed to catch the eye, its vibrant hue adds a pop of color to any ensemble. Featuring bold typographic elements, it injects a dose of urban edge into your look. Crafted with Superdry's signature quality and attention to detail, this tee offers both comfort and durability. Whether you're hitting the city streets or chilling with friends, its eye-catching color and playful typography ensure you stand out from the crowd with effortless style. Make a statement with this neon green masterpiece and let your personality shine.",
    cat: "Mens",
    pdf: pdf1,
  },
  {
    _id: "ricoh3",
    img: superdry_newm_6,
    productName: "Superdry Crystal Green",
    price: "450",
    color: "Green",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Crystal Green Typographic T-shirt - Dive into a sea of style with this captivating crystal green tee from Superdry. Inspired by the depths of the ocean, its tranquil hue exudes a sense of calm sophistication. Adorned with typographic elements, it adds a touch of urban edge to your ensemble. Crafted with Superdry's commitment to quality, this tee offers both comfort and durability. Whether you're strolling along the beach or exploring the city streets, its refreshing color and playful typography make a statement that's as bold as your adventurous spirit. Elevate your wardrobe with this crystal green gem and make waves wherever you go.",
    cat: "Mens",
    pdf: pdf1,
  },
  {
    _id: "ricoh4",
    img: superdry_newm_7,
    productName: "Superdry Dark Grey",
    price: "450",
    color: "Grey",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Gray Typographic T-shirt - Elevate your everyday wardrobe with this sleek and versatile tee from Superdry. Crafted in a timeless shade of gray, it's the epitome of understated style. Adorned with bold black typographic elements, it adds a contemporary edge to your look. Made with Superdry's commitment to quality, this tee offers both comfort and durability. Whether you're running errands or meeting friends, its classic color and playful typography ensure you stand out with effortless cool. Pair it with your favorite jeans or layer it under a jacket for a laid-back yet polished ensemble. Upgrade your wardrobe with this essential gray tee and make a statement without saying a word.",
    cat: "Mens",
    pdf: pdf1,
  },
  {
    _id: "ricoh5",
    img: superdry_newm_8,
    productName: "Superdry Dark Red",
    price: "450",
    color: "Red",
    badge: true,
    brand: "Superdry",
    des: "Introducing the Superdry Men's Dark Red Typographic T-shirt - Add a dash of sophistication to your casual ensemble with this striking dark red tee from Superdry. Crafted in a rich and bold hue, it exudes an air of refined elegance. Accentuated with sleek black typographic elements, it offers a contemporary twist to your look. Designed with Superdry's renowned attention to quality, this tee ensures both comfort and durability. Whether you're out for a night on the town or simply lounging with friends, its deep color and stylish typography make a statement that's impossible to ignore. Elevate your wardrobe with this essential dark red tee and step out in confidence and style.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "espson1",
    img: lacoste_newm_1,
    productName: "Lacoste Aqua Blue",
    price: "450",
    color: "Blue",
    badge: true,
    brand: "Lacoste",
    des: "Introducing the Lacoste Men's Polo-style Striped T-shirt - Elevate your casual wardrobe with this sophisticated polo-style tee from Lacoste. Crafted with Lacoste's signature attention to detail, this tee features a timeless design with a classic polo collar and striped pattern. Made with premium materials, it offers both comfort and style for everyday wear. Whether you're hitting the golf course or enjoying a day out, this Lacoste tee exudes sporty elegance. Pair it with chinos for a refined look or with jeans for a casual vibe. Make a statement with this versatile piece and showcase your classic style with confidence.",
    cat: "Mens",
    pdf: pdf1,
  },

  {
    _id: "espson2",
    img: lacoste_newm_2,
    productName: "Lacoste Grey Freefit",
    price: "450",
    color: "Gray",
    badge: true,
    brand: "Lacoste",
    des: "Introducing the Lacoste Men's Freefit Gray T-shirt - Redefine your casual style with this effortlessly cool tee from Lacoste. Designed with a relaxed and freefit silhouette, this gray t-shirt offers the ultimate in comfort and ease of movement. Crafted with Lacoste's signature attention to quality, it ensures durability for long-lasting wear. Whether you're lounging at home or exploring the city streets, this versatile tee is a must-have addition to your wardrobe. Pair it with joggers for a laid-back look or dress it up with jeans for a more polished ensemble. Embrace comfort and style with this essential gray tee from Lacoste.",
    cat: "Mens",
    pdf: pdf1,
  },
];
